#!/bin/sh

if [ "${VIM_SERVERNAME}" == '' ]; then 
    \vim "$*"
else
    vimdo() {
        \vim --servername "${VIM_SERVERNAME}" --remote-send "<C-l>:$*<CR>"
    }

    if [ "$*" != '' ]; then
        vimdo args "$@"
    else
        vimdo enew
    fi
fi
